python_library(
    name='redisearch_lib',
    sources=rglobs('*.py'),

    #provides=setup_py(
    #    name='redisearch',
    #    version='1.0',
    #    zip_safe=True,
    #    author="houzz",
    #    author_email="dev@houzz.com",
    #    description="redisearch",
    #)
)
